version: '3'
services:
  web:
    build:
      dockerfile: dev.Dockerfile
      context: ./
    ports:
    - "8080:3000"
    volumes:
    - .:/app
    environment:
      GOTIFY_PRE-SHARED-KEY: "123abc"
      GOTIFY_DEBUG-MODE: "true"
      GOTIFY_MOCK-MODE: "true"
      GOTIFY_GOOGLE-MAIL.KEYFILE: "gapps.json"