version: '3.4'
services:
  dev:
    build:
      dockerfile: dev.Dockerfile
      context: ./
      target: dev
    ports:
    - "8080:8080"
    - "8090:8090"
    volumes:
    - .:/app
    environment:
      GOTIFY_DEBUG-MODE: "true"
      GOTIFY_MOCK-MODE: "true"
      GOTIFY_GOOGLE-MAIL.KEYFILE: "gapps.json"
  dev-gen:
    build:
      dockerfile: dev.Dockerfile
      context: ./
      target: dev_gen
    volumes:
      - .:/app
    command: ./scripts/proto-watcher.sh
  swagger: # Generated swagger file i quite bad at the time of writing
    image: swaggerapi/swagger-ui
    ports:
      - "8000:8000"
    environment:
      PORT: "8000"
      SWAGGER_JSON: "/app/v1/apidocs.swagger.json"
    volumes:
      - ./api/swagger:/app